name: github-proxy
on:
  release:
    types:
      - published

jobs:
  build:
    name: Upload github-proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to quay.io
        run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build the Docker image
        run: |
          IMAGE_NAME="quay.io/alitman_storage_ocs/github-proxy:${GITHUB_REF##*/}"
        CONTAINER_RUNTIME=docker IMG="${IMAGE_NAME}" ${CONTAINER_RUNTIME} build -t ${IMG}
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Push the Docker image
        run: CONTAINER_RUNTIME=docker IMG="${{ env.IMAGE_NAME }}" ${CONTAINER_RUNTIME} push ${IMG}
